schema_version: 1

context:
  version: "2.3.0"

package:
  name: gflags
  version: ${{ version }}

source:
  url: https://github.com/gflags/gflags/archive/v${{ version }}.tar.gz
  sha256: f619a51371f41c0ad6837b2a98af9d4643b3371015d873887f7e8d3237320b2f

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  run_exports:
    - ${{ pin_subpackage('gflags', upper_bound='x.x') }}

tests:
  - script:
      - if: osx
        then: test -f ${PREFIX}/lib/libgflags.dylib
      - if: osx
        then: test -f ${PREFIX}/lib/libgflags_nothreads.dylib
      - if: linux
        then: test -f ${PREFIX}/lib/libgflags.so
      - if: linux
        then: test -f ${PREFIX}/lib/libgflags_nothreads.so
      - if: unix
        then: 
          - test ! -f ${PREFIX}/lib/libgflags.a
          - test ! -f ${PREFIX}/lib/libgflags_nothreads.a
        else:
          - if not exist %PREFIX%\\Library\\bin\\gflags.dll exit 1
          - if not exist %PREFIX%\\Library\\lib\\gflags.lib exit 1
          - if exist %PREFIX%\\Library\\lib\\gflags_static.lib exit 1

about:
  license: BSD-3-Clause
  license_file: COPYING.txt
  summary: A C++ library that implements commandline flags processing.
  homepage: https://github.com/gflags/gflags

extra:
  recipe-maintainers:
    - jakirkham
    - wesm
    - xhochy
